### ISSUE TITLE
Empty attributes list

### ISSUE THREAD

**Issue by engeir** [engeir/ncdump-rich#14]
netCDF file without attributes give an index error:

```txt
Traceback (most recent call last):
  File "/cluster/home/een023/.local/bin/ncdump-rich", line 10, in <module>
    sys.exit(main())
  File "/cluster/home/een023/.local/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/cluster/home/een023/.local/lib/python3.7/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/cluster/home/een023/.local/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/cluster/home/een023/.local/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/cluster/home/een023/.local/lib/python3.7/site-packages/ncdump_rich/__main__.py", line 30, in main
    ncd.ncdump(input, long=long, truecolor=format)
  File "/cluster/home/een023/.local/lib/python3.7/site-packages/ncdump_rich/ncdump.py", line 70, in ncdump
    if repr(nc_file.getncattr(nc_attr)[0]) != repr("\n"):
IndexError: string index out of range
```

**Comment by engeir** [comment]
Fixed by 06a99d900ae5a9f4a6ef6357b60c497a244ceb47.
